# Generated by Django 4.0.6 on 2023-08-30 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('raza', models.CharField(max_length=255)),
                ('num_vac', models.IntegerField(null=True)),
            ],
        ),
    ]
