# Generated by Django 4.0.6 on 2023-08-30 01:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pet',
            old_name='raza',
            new_name='especie',
        ),
        migrations.AddField(
            model_name='pet',
            name='nacimiento',
            field=models.DateField(default=datetime.date(1900, 1, 1)),
        ),
    ]
